## Data Analytics Practicals 

In [1]:
import numpy as np

In [2]:
## Practical 2 - Create a 1D array of numbers from 1 to 20. Reshape it into a 4x5 matrix (2D array) and print the shape and data type. 

array1 =  np.arange(1,21)
print(f"The Created 1D Array - {array1}")

The Created 1D Array - [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [7]:
array2 = array1.reshape(4,5)
print(f"Updated 1D Array into a 4x5 Array - {array2}")

array2.dtype

Updated 1D Array into a 4x5 Array - [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


dtype('int64')