## Data Analytics Practicals 

In [1]:
import numpy as np

In [10]:
## Practical 2 - Create a 1D array of numbers from 1 to 20. Reshape it into a 4x5 matrix (2D array) and print the shape and data type. 

array1 =  np.arange(1,21)
print(f"The Created 1D Array - {array1}")


array2 = array1.reshape(4,5)
print(f"Updated 1D Array into a 4x5 Array - {array2}")

array2.dtype

The Created 1D Array - [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Updated 1D Array into a 4x5 Array - [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


dtype('int64')

In [28]:
## Practical 3 - Create an array of 5 product prices and perform mathematical operations on entire datasets at once. 

prices = np.array([222,344,199.5,62.2,205])


print(f"Original Prices - {prices}")


print(f"Lowest value of a item - {np.min(prices)}")
print(f"Highest value of a item - {np.max(prices)}")
print(f"Average value of items in prices - {np.mean(prices)}")
print(f"Sum of all values of items in prices - {np.sum(prices)}")

discounted_prices = prices * 0.80
print(f"Discount on items in prices - {discounted_prices}")

gst_on_prices = prices * 1.18
print(f"GST on items in prices - {gst_on_prices}")

Original Prices - [222.  344.  199.5  62.2 205. ]
Lowest value of a item - 62.2
Highest value of a item - 344.0
Average value of items in prices - 206.54000000000002
Sum of all values of items in prices - 1032.7
Discount on items in prices - [177.6  275.2  159.6   49.76 164.  ]
GST on items in prices - [261.96  405.92  235.41   73.396 241.9  ]


In [ ]:
import pandas as pd


## Practical 4 - Create a Pandas DataFrame from a dictionary of 5 employees (ID, Name, Salary). Display the first 3 rows (head) and check column types (info). 
data = {
    "ID " : ["100","101","102","103","104"],
    "Employee": ["Soham","Mohan","Rohan","Riya","Purva"],
    "Salary": ["50000","60000","70000","80000","90000"]
}

df = pd.DataFrame(data)

,ID,Employee,Salary
0,100,Soham,50000
1,101,Mohan,60000
2,102,Rohan,70000
3,103,Riya,80000
4,104,Purva,90000
